name: minimoon-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
    - name: Freeze config
      run: python miniminimoon_immutability.py freeze --repo .
    - name: Evaluate sample
      run: python miniminimoon_cli.py evaluate tests/sample_pdm.txt --repo . --rubric RUBRIC_SCORING.json
    - name: Verify post-execution
      run: python miniminimoon_cli.py verify --repo .
    - name: Rubric check 1:1
      run: python tools/rubric_check.py
    - name: Trace matrix
      run: python tools/trace_matrix.py
