# Performance Budgets for 11 Canonical Pipeline Nodes
# =======================================================
# Per-node latency targets with 10% tolerance for CI/CD gates
# All budgets are p95 latency in milliseconds

budgets:
  # Core Processing Nodes
  sanitization:
    p95_ms: 2.0
    p99_ms: 3.0
    tolerance_pct: 10.0
    description: "Text sanitization and normalization"
    
  plan_processing:
    p95_ms: 3.0
    p99_ms: 5.0
    tolerance_pct: 10.0
    description: "Metadata extraction and plan parsing"
    
  document_segmentation:
    p95_ms: 4.0
    p99_ms: 6.0
    tolerance_pct: 10.0
    description: "Document chunking and paragraph segmentation"
  
  # Embedding Node (optimized with batching)
  embedding:
    p95_ms: 50.0
    p99_ms: 80.0
    tolerance_pct: 10.0
    description: "Batch embedding generation with MPNet/MiniLM"
    optimization:
      batching_enabled: true
      batch_size: 32
      cache_enabled: true
  
  # Detection Nodes
  responsibility_detection:
    p95_ms: 10.0
    p99_ms: 15.0
    tolerance_pct: 10.0
    description: "spaCy NER + lexical pattern matching"
    
  contradiction_detection:
    p95_ms: 8.0
    p99_ms: 12.0
    tolerance_pct: 10.0
    description: "Semantic contradiction analysis"
    
  monetary_detection:
    p95_ms: 5.0
    p99_ms: 8.0
    tolerance_pct: 10.0
    description: "Currency and budget value extraction"
  
  # Scoring and Validation Nodes
  feasibility_scoring:
    p95_ms: 6.0
    p99_ms: 10.0
    tolerance_pct: 10.0
    description: "Multi-dimensional feasibility scoring"
    
  causal_detection:
    p95_ms: 7.0
    p99_ms: 11.0
    tolerance_pct: 10.0
    description: "PDET causal pattern detection"
    
  teoria_cambio:
    p95_ms: 15.0
    p99_ms: 25.0
    tolerance_pct: 10.0
    description: "Theory of change graph construction"
    
  dag_validation:
    p95_ms: 10.0
    p99_ms: 18.0
    tolerance_pct: 10.0
    description: "DAG acyclicity validation"

# Special Performance Targets
special_targets:
  contract_validation_ROUTING:
    p95_ms: 5.0
    p99_ms: 8.0
    tolerance_pct: 10.0
    description: "Contract validation with caching optimization"
    
  PERMUTATION_INVARIANCE:
    p95_ms: 0.5
    p99_ms: 1.0
    tolerance_pct: 10.0
    description: "Mass conservation check"
    
  BUDGET_MONOTONICITY:
    p95_ms: 0.15
    p99_ms: 0.25
    tolerance_pct: 10.0
    description: "Transport matrix doubly-stochastic check"

# Circuit Breaker Configuration
circuit_breakers:
  recovery_time_threshold_seconds: 2.0
  failure_threshold: 5
  success_threshold: 2
  timeout_seconds: 60.0
  
  # Fault-prone operations requiring circuit breakers
  protected_operations:
    - embedding
    - responsibility_detection
    - contradiction_detection
    - causal_detection
    - teoria_cambio
    - dag_validation

# CI/CD Gates
cicd:
  # Fail build when benchmarks exceed budget + tolerance
  fail_on_budget_violation: true
  
  # Require minimum iterations for statistical significance
  min_benchmark_iterations: 100
  
  # P95/P99 percentile tracking
  percentiles:
    - 50
    - 95
    - 99
  
  # Generate performance reports
  reports:
    json_output: "performance_report.json"
    prometheus_output: "performance_metrics.prom"
    html_dashboard: "performance_dashboard.html"

# Prometheus Metrics Configuration
prometheus:
  # Metric naming convention
  namespace: "miniminimoon"
  subsystem: "pipeline"
  
  # Export intervals
  export_interval_seconds: 10
  
  # Histogram buckets for latency (milliseconds)
  latency_buckets:
    - 1
    - 2
    - 5
    - 10
    - 20
    - 50
    - 100
    - 200
    - 500
    - 1000
    - 2000
    - 5000

# Alerting Rules
alerting:
  # Alert on p95 latency exceeding node-specific budgets
  latency_sla_violations:
    enabled: true
    severity: "warning"
    threshold_multiplier: 1.0  # Alert when p95 exceeds budget
    
  # Alert on circuit breaker state transitions
  circuit_breaker_alerts:
    enabled: true
    severities:
      open: "critical"
      half_open: "warning"
      closed: "info"
  
  # Alert channels
  channels:
    - type: "prometheus_alertmanager"
      endpoint: "http://localhost:9093"
    - type: "log"
      level: "ERROR"
