use_clean_versions: true
paths:
  full: "../../bundles/decalogo-industrial.latest.clean.json"
  industrial: "../../bundles/decalogo-industrial.latest.clean.json"
  dnp: "../../standards/dnp-standards.latest.clean.json"
crosswalk: "out/crosswalk.latest.json"
autoload: true
fail_fast: true
