use_clean_versions: true
paths:
  full: "../../decalogo-industrial.latest.clean.json"
  industrial: "../../decalogo-industrial.latest.clean.json"
  dnp: "../../dnp-standards.latest.clean.json"
crosswalk: "out/crosswalk.latest.json"
autoload: true
fail_fast: true
